/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface BCdpScoreConnectorContract
  extends Truffle.Contract<BCdpScoreConnectorInstance> {
  "new"(
    score_: string,
    meta?: Truffle.TransactionDetails
  ): Promise<BCdpScoreConnectorInstance>;
}

type AllEvents = never;

export interface BCdpScoreConnectorInstance extends Truffle.ContractInstance {
  left(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  score(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    left(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    score(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
