/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface BCdpScoreContract extends Truffle.Contract<BCdpScoreInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<BCdpScoreInstance>;
}

export interface OwnershipTransferred {
  name: "OwnershipTransferred";
  args: {
    previousOwner: string;
    newOwner: string;
    0: string;
    1: string;
  };
}

type AllEvents = OwnershipTransferred;

export interface BCdpScoreInstance extends Truffle.ContractInstance {
  GLOBAL_USER(txDetails?: Truffle.TransactionDetails): Promise<string>;

  artAsset(
    ilk: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  checkpoints(
    arg0: string,
    arg1: string,
    arg2: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN]>;

  getArtGlobalScore(
    ilk: string,
    time: number | BN | string,
    spinStart: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getArtScore(
    cdp: number | BN | string,
    ilk: string,
    time: number | BN | string,
    spinStart: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getCurrentBalance(
    user: string,
    asset: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getScore(
    user: string,
    asset: string,
    time: number | BN | string,
    spinStart: number | BN | string,
    checkPointHint: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  isOwner(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  manager(txDetails?: Truffle.TransactionDetails): Promise<string>;

  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  renounceOwnership: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  setManager: {
    (newManager: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newManager: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newManager: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newManager: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  slashScore: {
    (
      maliciousCdp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      maliciousCdp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      maliciousCdp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      maliciousCdp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  spin: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  start(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  transferOwnership: {
    (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateScore: {
    (
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  user(
    cdp: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  userScore(
    arg0: string,
    arg1: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN]>;

  methods: {
    GLOBAL_USER(txDetails?: Truffle.TransactionDetails): Promise<string>;

    artAsset(
      ilk: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    checkpoints(
      arg0: string,
      arg1: string,
      arg2: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN]>;

    getArtGlobalScore(
      ilk: string,
      time: number | BN | string,
      spinStart: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getArtScore(
      cdp: number | BN | string,
      ilk: string,
      time: number | BN | string,
      spinStart: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getCurrentBalance(
      user: string,
      asset: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getScore(
      user: string,
      asset: string,
      time: number | BN | string,
      spinStart: number | BN | string,
      checkPointHint: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    isOwner(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

    manager(txDetails?: Truffle.TransactionDetails): Promise<string>;

    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    renounceOwnership: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    setManager: {
      (newManager: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newManager: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newManager: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newManager: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    slashScore: {
      (
        maliciousCdp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        maliciousCdp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        maliciousCdp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        maliciousCdp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    spin: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    start(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    transferOwnership: {
      (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateScore: {
      (
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    user(
      cdp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    userScore(
      arg0: string,
      arg1: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
