/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface BCdpScoreLikeContract
  extends Truffle.Contract<BCdpScoreLikeInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<BCdpScoreLikeInstance>;
}

type AllEvents = never;

export interface BCdpScoreLikeInstance extends Truffle.ContractInstance {
  updateScore: {
    (
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      cdp: number | BN | string,
      ilk: string,
      dink: number | BN | string,
      dart: number | BN | string,
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    updateScore: {
      (
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        cdp: number | BN | string,
        ilk: string,
        dink: number | BN | string,
        dart: number | BN | string,
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
