/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface BComptrollerLikeContract
  extends Truffle.Contract<BComptrollerLikeInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<BComptrollerLikeInstance>;
}

type AllEvents = never;

export interface BComptrollerLikeInstance extends Truffle.ContractInstance {
  c2b(ctoken: string, txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    c2b(
      ctoken: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
