/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface CDelegateInterfaceContract
  extends Truffle.Contract<CDelegateInterfaceInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<CDelegateInterfaceInstance>;
}

type AllEvents = never;

export interface CDelegateInterfaceInstance extends Truffle.ContractInstance {
  _becomeImplementation: {
    (data: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(data: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  _resignImplementation: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  implementation(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    _becomeImplementation: {
      (data: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(data: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    _resignImplementation: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    implementation(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
