/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ComptrollerBorkedContract
  extends Truffle.Contract<ComptrollerBorkedInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ComptrollerBorkedInstance>;
}

type AllEvents = never;

export interface ComptrollerBorkedInstance extends Truffle.ContractInstance {
  _become: {
    (
      unitroller: string,
      _oracle: string,
      _closeFactorMantissa: number | BN | string,
      _maxAssets: number | BN | string,
      _reinitializing: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      unitroller: string,
      _oracle: string,
      _closeFactorMantissa: number | BN | string,
      _maxAssets: number | BN | string,
      _reinitializing: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      unitroller: string,
      _oracle: string,
      _closeFactorMantissa: number | BN | string,
      _maxAssets: number | BN | string,
      _reinitializing: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      unitroller: string,
      _oracle: string,
      _closeFactorMantissa: number | BN | string,
      _maxAssets: number | BN | string,
      _reinitializing: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    _become: {
      (
        unitroller: string,
        _oracle: string,
        _closeFactorMantissa: number | BN | string,
        _maxAssets: number | BN | string,
        _reinitializing: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        unitroller: string,
        _oracle: string,
        _closeFactorMantissa: number | BN | string,
        _maxAssets: number | BN | string,
        _reinitializing: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        unitroller: string,
        _oracle: string,
        _closeFactorMantissa: number | BN | string,
        _maxAssets: number | BN | string,
        _reinitializing: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        unitroller: string,
        _oracle: string,
        _closeFactorMantissa: number | BN | string,
        _maxAssets: number | BN | string,
        _reinitializing: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
