/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface DsAuthorityContract
  extends Truffle.Contract<DsAuthorityInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<DsAuthorityInstance>;
}

type AllEvents = never;

export interface DsAuthorityInstance extends Truffle.ContractInstance {
  canCall(
    src: string,
    dst: string,
    sig: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    canCall(
      src: string,
      dst: string,
      sig: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
