/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface FakeBComptrollerContract
  extends Truffle.Contract<FakeBComptrollerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<FakeBComptrollerInstance>;
}

type AllEvents = never;

export interface FakeBComptrollerInstance extends Truffle.ContractInstance {
  c2b(a: string, txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    c2b(a: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
