/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IbComptrollerContract
  extends Truffle.Contract<IbComptrollerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IbComptrollerInstance>;
}

type AllEvents = never;

export interface IbComptrollerInstance extends Truffle.ContractInstance {
  b2c(bToken: string, txDetails?: Truffle.TransactionDetails): Promise<string>;

  c2b(cToken: string, txDetails?: Truffle.TransactionDetails): Promise<string>;

  isBToken(
    bToken: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  isCToken(
    cToken: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    b2c(
      bToken: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    c2b(
      cToken: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    isBToken(
      bToken: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    isCToken(
      cToken: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
