/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IScoringConfigContract
  extends Truffle.Contract<IScoringConfigInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IScoringConfigInstance>;
}

type AllEvents = never;

export interface IScoringConfigInstance extends Truffle.ContractInstance {
  getGlobalScore(
    token: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getUserScore(
    user: string,
    token: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    getGlobalScore(
      token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getUserScore(
      user: string,
      token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
