/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface PriceFeedLikeContract
  extends Truffle.Contract<PriceFeedLikeInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<PriceFeedLikeInstance>;
}

type AllEvents = never;

export interface PriceFeedLikeInstance extends Truffle.ContractInstance {
  read(ilk: string, txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    read(ilk: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
