/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface RegistryLikeContract
  extends Truffle.Contract<RegistryLikeInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<RegistryLikeInstance>;
}

type AllEvents = never;

export interface RegistryLikeInstance extends Truffle.ContractInstance {
  avatarLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  avatars(
    i: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  comptroller(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getAvatar: {
    (user: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(user: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    sendTransaction(
      user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  score(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    avatarLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    avatars(
      i: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    comptroller(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getAvatar: {
      (user: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      sendTransaction(
        user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    score(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
