/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TokenErrorReporterContract
  extends Truffle.Contract<TokenErrorReporterInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<TokenErrorReporterInstance>;
}

export interface Failure {
  name: "Failure";
  args: {
    error: BN;
    info: BN;
    detail: BN;
    0: BN;
    1: BN;
    2: BN;
  };
}

type AllEvents = Failure;

export interface TokenErrorReporterInstance extends Truffle.ContractInstance {
  methods: {};

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
